# Generated by Django 5.0 on 2026-01-19 02:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="KnowledgeCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "case_id",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                (
                    "summary_text",
                    models.TextField(help_text="Clinical summary of the case"),
                ),
                ("diagnosis", models.CharField(max_length=500)),
                ("outcome", models.TextField(blank=True, null=True)),
                (
                    "embedding",
                    models.BinaryField(
                        blank=True,
                        help_text="Numpy array of embedding stored as binary",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["case_id"],
            },
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "patient_id",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                (
                    "age",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(150),
                        ]
                    ),
                ),
                (
                    "sex",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        max_length=10,
                    ),
                ),
                ("chief_complaint", models.TextField()),
                ("symptoms", models.TextField(help_text="Free-text symptoms")),
                ("past_medical_history", models.TextField(blank=True, null=True)),
                ("medications", models.TextField(blank=True, null=True)),
                ("clinical_notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Labs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lab_results",
                    models.TextField(help_text="Free-text or structured lab results"),
                ),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "patient",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="labs",
                        to="diagnosis.patient",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Labs",
            },
        ),
        migrations.CreateModel(
            name="DiagnosisResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "differential_diagnoses",
                    models.JSONField(
                        help_text="List of diagnoses with likelihood percentages"
                    ),
                ),
                (
                    "triage_level",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "explanation",
                    models.TextField(help_text="Medical reasoning and explanation"),
                ),
                (
                    "confidence_score",
                    models.FloatField(
                        help_text="Model confidence score (0-1)",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "retrieved_cases",
                    models.JSONField(
                        help_text="List of retrieved case IDs used for reasoning"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diagnosis_results",
                        to="diagnosis.patient",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ClinicalSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "summary_text",
                    models.TextField(help_text="Structured clinical summary"),
                ),
                (
                    "embedding",
                    models.BinaryField(
                        blank=True,
                        help_text="Numpy array of embedding stored as binary",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "patient",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clinical_summary",
                        to="diagnosis.patient",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Clinical Summaries",
            },
        ),
        migrations.CreateModel(
            name="Vitals",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "blood_pressure_systolic",
                    models.IntegerField(blank=True, help_text="mmHg", null=True),
                ),
                (
                    "blood_pressure_diastolic",
                    models.IntegerField(blank=True, help_text="mmHg", null=True),
                ),
                (
                    "heart_rate",
                    models.IntegerField(blank=True, help_text="bpm", null=True),
                ),
                (
                    "respiratory_rate",
                    models.IntegerField(blank=True, help_text="breaths/min", null=True),
                ),
                (
                    "oxygen_saturation",
                    models.FloatField(
                        blank=True,
                        help_text="SpO2 %",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "temperature",
                    models.FloatField(blank=True, help_text="°F", null=True),
                ),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "patient",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vitals",
                        to="diagnosis.patient",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Vitals",
            },
        ),
    ]
