# Generated by Django 5.0 on 2026-01-22 10:17

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="KnowledgeCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "case_id",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                (
                    "summary_text",
                    models.TextField(help_text="Clinical summary of the case"),
                ),
                ("diagnosis", models.CharField(max_length=500)),
                ("outcome", models.TextField(blank=True, null=True)),
                (
                    "embedding",
                    models.BinaryField(
                        blank=True,
                        help_text="Numpy array of embedding stored as binary",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["case_id"],
            },
        ),
        migrations.CreateModel(
            name="LLMUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_name", models.CharField(db_index=True, max_length=100)),
                (
                    "api_key_fingerprint",
                    models.CharField(
                        db_index=True,
                        help_text="SHA256 hash of API key (first 12 chars)",
                        max_length=64,
                    ),
                ),
                (
                    "date",
                    models.DateField(db_index=True, default=django.utils.timezone.now),
                ),
                ("count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-date", "model_name"],
                "unique_together": {("model_name", "api_key_fingerprint", "date")},
            },
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "patient_id",
                    models.CharField(
                        db_index=True,
                        help_text="Human-readable ID like P-ER-001",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True, help_text="Patient's date of birth", null=True
                    ),
                ),
                (
                    "age",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(150),
                        ]
                    ),
                ),
                (
                    "sex",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        max_length=10,
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "address",
                    models.TextField(blank=True, help_text="Full address", null=True),
                ),
                (
                    "emergency_contact_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "emergency_contact_phone",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("past_medical_history", models.TextField(blank=True, null=True)),
                ("medications", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["last_name", "first_name"],
                        name="diagnosis_p_last_na_b59593_idx",
                    ),
                    models.Index(
                        fields=["phone_number"], name="diagnosis_p_phone_n_d9b5f8_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("DOCTOR", "Doctor"),
                            ("ADMIN", "Administrator"),
                            ("STAFF", "Staff"),
                        ],
                        default="STAFF",
                        max_length=10,
                    ),
                ),
                ("department", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "license_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Visit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "visit_number",
                    models.IntegerField(
                        help_text="Sequential visit number for this patient"
                    ),
                ),
                (
                    "visit_type",
                    models.CharField(
                        choices=[
                            ("INITIAL", "Initial Visit"),
                            ("FOLLOW_UP", "Follow-up Visit"),
                            ("EMERGENCY", "Emergency"),
                        ],
                        default="INITIAL",
                        max_length=20,
                    ),
                ),
                ("chief_complaint", models.TextField()),
                ("symptoms", models.TextField(help_text="Free-text symptoms")),
                ("clinical_notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visits",
                        to="diagnosis.patient",
                    ),
                ),
            ],
            options={
                "ordering": ["patient", "visit_number"],
            },
        ),
        migrations.CreateModel(
            name="Labs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lab_results",
                    models.TextField(help_text="Free-text or structured lab results"),
                ),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "visit",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="labs",
                        to="diagnosis.visit",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Labs",
            },
        ),
        migrations.CreateModel(
            name="DiagnosisResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "case_fingerprint",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Deterministic hash of visit presentation",
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "differential_diagnoses",
                    models.JSONField(
                        help_text="List of diagnoses with likelihood percentages"
                    ),
                ),
                (
                    "triage_level",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "explanation",
                    models.TextField(help_text="Medical reasoning and explanation"),
                ),
                (
                    "confidence_score",
                    models.FloatField(
                        help_text="Model confidence score (0-1)",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "retrieved_cases",
                    models.JSONField(
                        help_text="List of retrieved case IDs used for reasoning"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "source_result",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reused_results",
                        to="diagnosis.diagnosisresult",
                    ),
                ),
                (
                    "visit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diagnosis_results",
                        to="diagnosis.visit",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DiagnosisJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("case_fingerprint", models.CharField(db_index=True, max_length=64)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="diagnosis_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "diagnosis",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="origin_jobs",
                        to="diagnosis.diagnosisresult",
                    ),
                ),
                (
                    "reuse_source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reuse_jobs",
                        to="diagnosis.diagnosisresult",
                    ),
                ),
                (
                    "visit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diagnosis_jobs",
                        to="diagnosis.visit",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ClinicalSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "summary_text",
                    models.TextField(help_text="Structured clinical summary"),
                ),
                (
                    "embedding",
                    models.BinaryField(
                        blank=True,
                        help_text="Numpy array of embedding stored as binary",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "visit",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clinical_summary",
                        to="diagnosis.visit",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Clinical Summaries",
            },
        ),
        migrations.CreateModel(
            name="Vitals",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "blood_pressure_systolic",
                    models.IntegerField(blank=True, help_text="mmHg", null=True),
                ),
                (
                    "blood_pressure_diastolic",
                    models.IntegerField(blank=True, help_text="mmHg", null=True),
                ),
                (
                    "heart_rate",
                    models.IntegerField(blank=True, help_text="bpm", null=True),
                ),
                (
                    "respiratory_rate",
                    models.IntegerField(blank=True, help_text="breaths/min", null=True),
                ),
                (
                    "oxygen_saturation",
                    models.FloatField(
                        blank=True,
                        help_text="SpO2 %",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "temperature",
                    models.FloatField(blank=True, help_text="°F", null=True),
                ),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "visit",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vitals",
                        to="diagnosis.visit",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Vitals",
            },
        ),
        migrations.AddIndex(
            model_name="visit",
            index=models.Index(
                fields=["patient", "visit_number"],
                name="diagnosis_v_patient_11f9bd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="visit",
            index=models.Index(
                fields=["created_at"], name="diagnosis_v_created_f8a13c_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="visit",
            unique_together={("patient", "visit_number")},
        ),
        migrations.AddIndex(
            model_name="diagnosisresult",
            index=models.Index(
                fields=["case_fingerprint"], name="diagnosis_d_case_fi_ea514b_idx"
            ),
        ),
    ]
