# Generated by Django 5.0 on 2026-01-19 02:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diagnosis", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LLMUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_name", models.CharField(db_index=True, max_length=100)),
                (
                    "api_key_fingerprint",
                    models.CharField(
                        db_index=True,
                        help_text="SHA256 hash of API key (first 12 chars)",
                        max_length=64,
                    ),
                ),
                (
                    "date",
                    models.DateField(db_index=True, default=django.utils.timezone.now),
                ),
                ("count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-date", "model_name"],
                "unique_together": {("model_name", "api_key_fingerprint", "date")},
            },
        ),
    ]
