# Generated by Django 5.0 on 2026-01-21 03:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diagnosis", "0003_userprofile"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DiagnosisJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("case_fingerprint", models.CharField(db_index=True, max_length=64)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="diagnosisresult",
            name="case_fingerprint",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Deterministic hash of patient presentation",
                max_length=64,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="diagnosisresult",
            name="source_result",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reused_results",
                to="diagnosis.diagnosisresult",
            ),
        ),
        migrations.AddIndex(
            model_name="diagnosisresult",
            index=models.Index(
                fields=["case_fingerprint"], name="diagnosis_d_case_fi_ea514b_idx"
            ),
        ),
        migrations.AddField(
            model_name="diagnosisjob",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="diagnosis_jobs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="diagnosisjob",
            name="diagnosis",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="origin_jobs",
                to="diagnosis.diagnosisresult",
            ),
        ),
        migrations.AddField(
            model_name="diagnosisjob",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="diagnosis_jobs",
                to="diagnosis.patient",
            ),
        ),
        migrations.AddField(
            model_name="diagnosisjob",
            name="reuse_source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reuse_jobs",
                to="diagnosis.diagnosisresult",
            ),
        ),
    ]
